//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.DataProvider.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUONGPHO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DUONGPHO()
        {
            this.KHACHHANGs = new HashSet<KHACHHANG>();
        }
    
        public string MADP { get; set; }
        public string DUONGPHU { get; set; }
        public string TENDP { get; set; }
        public string TENHD { get; set; }
        public string MAKV { get; set; }
        public string MAPHUONG { get; set; }
        public string TENPHUONG { get; set; }
        public string MADPCU { get; set; }
        public Nullable<int> BUOCNHAY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHACHHANG> KHACHHANGs { get; set; }
    }
}
