//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.DataProvider.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Account_Capability
    {
        public int ID { get; set; }
        public long Account { get; set; }
        public string Capability { get; set; }
        public Nullable<bool> IsPrimary { get; set; }
    }
}
